name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  enable-auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: [self-hosted, linux, arm64]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          echo "Enabling auto-merge for $PR_URL ..."
          gh pr merge "$PR_URL" --merge --auto --delete-branch
